### PR TITLE
match weather home path like the rest of the data

### PR DESCRIPTION
**Pull request by sdtaylor**
the abundance data was being sourced from `~`, while the weather data from `cwd()`

### CODE REVIEW

**Comment by ethanwhite** [comment]
`abundance` defaults to `~` but also allows changing the path in the arguments. Is there any reason not to follow the same structure here?

**Comment by sdtaylor** [comment]
good point

**Comment by ethanwhite** [comment]
Thanks. Looks great. Just waiting on the tests to pass.

**Comment by sdtaylor** [comment]
:cold_sweat:

**Comment by ethanwhite** [comment]
😌

**Pull request merged**
