### PR TITLE
Namespaceissues

### PR DESCRIPTION
**Pull request by gmyenni**

### CODE REVIEW

**Comment by gmyenni** [comment]
The three tests failing are the first three regression tests. The fourth regression test, which uses `incomplete=T` and `unknowns=T` is passing. So the issue has got to be with a change in how one of those is handled. I suspect this is actually a change we want, and I just need to update the hashes, but I can't find the actual change to confirm. @emchristensen ? @bleds22e ?

**Comment by emchristensen** [comment]
Could it be line 41? reading in Portal_rodent_species.csv I seem to have added "stringsAsFactors=F"
That would cause things to be different in an invisible way

**Comment by emchristensen** [comment]
Aha, we also changed some left_joins to right_joins (line 105-115) and right_join to left_join (line 237-241).  I can't remember why we did that.

**Comment by bleds22e** [comment]
I think it had something to do with some of the column names we were having issues with, but that should be fixed now?

**Comment by gmyenni** [comment]
Woot!

**Pull request merged**
